// ============================================================
// Photo manifest
// This file lists every photograph shown in the gallery.
// It is automatically regenerated by update-gallery.ps1 when
// new photographs are added to the photos/ folder.
//
// Each entry:
//   src:     relative path to the image file inside photos/
//   caption: text shown under/over the image (edit freely)
// ============================================================
const PHOTOS = [
  { src: "photos/photo1.svg", caption: "Photo 1" },
  { src: "photos/photo2.svg", caption: "Photo 2" },
  { src: "photos/photo3.svg", caption: "Photo 3" },
  { src: "photos/photo4.svg", caption: "Photo 4" },
  { src: "photos/photo5.svg", caption: "Photo 5" },
  { src: "photos/photo6.svg", caption: "Photo 6" }
];
