// ============================================================
// photos.js - Photo manifest (auto-generated by update-gallery.ps1)
// Generated: 2026-08-13 10:44:58
// To add/remove photos: update the source folder and re-run
//   .\update-gallery.ps1
// ============================================================
window.PHOTOS = [
  { src: "photos/Akola LC gate no .83 on 17-4-26.jpg", caption: "Akola Lc Gate No .83 On 17 4 26" },
  { src: "photos/Akola pannel room 17.04.26.jpg", caption: "Akola Pannel Room 17.04.26" },
  { src: "photos/Akola TSS inspection on 17-4-26.jpg", caption: "Akola Tss Inspection On 17 4 26" },
  { src: "photos/Akola yard inspection.jpg", caption: "Akola Yard Inspection" },
  { src: "photos/Audit of IGP RRI Relay Room.jpg", caption: "Audit Of Igp Rri Relay Room" },
  { src: "photos/Bridge Inspection in SUR div.jpg", caption: "Bridge Inspection In Sur Div" },
  { src: "photos/BSL passenger lobby 17.04.26.jpg", caption: "Bsl Passenger Lobby 17.04.26" },
  { src: "photos/DRT Ultrasonic testerat KWV.jpg", caption: "Drt Ultrasonic Testerat Kwv" },
  { src: "photos/Engg Gate LC-1 DIWA-PNVL.jpg", caption: "Engg Gate Lc 1 Diwa Pnvl" },
  { src: "photos/GM inspection of DD Lobby  07.02.26.jpg", caption: "Gm Inspection Of Dd Lobby 07.02.26" },
  { src: "photos/KWV Pway Depot.jpg", caption: "Kwv Pway Depot" },
  { src: "photos/Multai station inspection by GM 24.12.2025.jpg", caption: "Multai Station Inspection By Gm 24.12.2025" },
  { src: "photos/SUR lobby.jpg", caption: "Sur Lobby" }
];
