// ============================================================
// photos.js - Photo manifest (auto-generated by update-gallery.ps1)
// Generated: 2026-08-13 10:05:34
// To add/remove photos: update the source folder and re-run
//   .\update-gallery.ps1
// ============================================================
window.PHOTOS = [
  { src: "photos/beto_mdp-hummingbird-10407977_1920.jpg", caption: "Beto Mdp Hummingbird 10407977 1920" },
  { src: "photos/biancavandijk-ghost-10360492_1920.jpg", caption: "Biancavandijk Ghost 10360492 1920" },
  { src: "photos/haninabz-coffee-cup-10209143_1920.png", caption: "Haninabz Coffee Cup 10209143 1920" },
  { src: "photos/mbrajeev-bird-10386158_1920.jpg", caption: "Mbrajeev Bird 10386158 1920" },
  { src: "photos/my_shot-bali-10400105_1920.jpg", caption: "My Shot Bali 10400105 1920" }
];
