# =============================================================
# update-gallery.ps1
# =============================================================
# PURPOSE:
#   Copies photographs from your local source folder into the
#   repository's photos/ directory, regenerates photos.js
#   (the image manifest), and optionally commits and pushes
#   the changes to GitHub so GitHub Pages updates automatically.
#
# HOW TO RUN (one-time setup):
#   1. Install Git for Windows: https://git-scm.com/
#   2. Clone the repository once:
#      git clone https://github.com/mshikhar1/intranet-photo-gallery.git
#      cd intranet-photo-gallery
#   3. Run this script from inside the cloned folder:
#      .\update-gallery.ps1
#
# HOW TO UPDATE PHOTOS LATER:
#   - Add/remove photos from $SourceFolder
#   - Run .\update-gallery.ps1 again
#   - GitHub Pages will update automatically within ~60 seconds
#
# NOTE: This script does NOT delete your original photographs.
#       It copies them. Originals remain in $SourceFolder.
# =============================================================

# ---- CONFIGURATION ---- Edit these variables if needed ----

# Source folder containing your photographs
$SourceFolder = "C:\Users\pc365\Desktop\IntranetGalleyCrousalPhotos"

# Destination photos/ folder (relative to where you run the script)
$DestFolder = Join-Path $PSScriptRoot "photos"

# photos.js manifest path
$ManifestPath = Join-Path $PSScriptRoot "photos.js"

# Supported image extensions
$Extensions = @("*.jpg", "*.jpeg", "*.png", "*.webp", "*.gif", "*.svg", "*.bmp", "*.tiff", "*.tif")

# Commit and push to GitHub automatically? Set to $false to skip.
$AutoCommitAndPush = $true

# Git commit message
$CommitMessage = "Update gallery photographs"

# ---- END CONFIGURATION ----

Write-Host ""
Write-Host "=== Photo Gallery Updater ==="
Write-Host ""

# Verify source folder exists
if (-not (Test-Path $SourceFolder)) {
    Write-Error "Source folder not found: $SourceFolder"
    Write-Host "Please update the value of `$SourceFolder in this script."
    exit 1
}

# Create destination folder if it doesn't exist
if (-not (Test-Path $DestFolder)) {
    New-Item -ItemType Directory -Path $DestFolder | Out-Null
    Write-Host "Created photos/ folder."
}

# Collect all image files from source
$ImageFiles = @()
foreach ($ext in $Extensions) {
    $ImageFiles += Get-ChildItem -Path $SourceFolder -Filter $ext -File
}

if ($ImageFiles.Count -eq 0) {
    Write-Warning "No image files found in: $SourceFolder"
    Write-Host "Supported formats: JPG, JPEG, PNG, WEBP, GIF, SVG, BMP, TIFF"
    exit 1
}

Write-Host "Found $($ImageFiles.Count) image(s) in source folder."
Write-Host ""

# Copy images to photos/ (skip if already identical using hash)
$Copied = 0
$Skipped = 0
foreach ($file in $ImageFiles) {
    $destFile = Join-Path $DestFolder $file.Name
    $doCopy = $true
    if (Test-Path $destFile) {
        $srcHash = (Get-FileHash -Path $file.FullName -Algorithm MD5).Hash
        $dstHash = (Get-FileHash -Path $destFile -Algorithm MD5).Hash
        if ($srcHash -eq $dstHash) {
            $doCopy = $false
            $Skipped++
        }
    }
    if ($doCopy) {
        Copy-Item -Path $file.FullName -Destination $destFile -Force
        Write-Host "  Copied: $($file.Name)"
        $Copied++
    }
}

Write-Host ""
Write-Host "Copied: $Copied file(s)  |  Skipped (unchanged): $Skipped file(s)"
Write-Host ""

# Function to turn filename into a readable caption
function Get-Caption($filename) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($filename)
    $name = $name -replace '[_\-]+', ' '
    # Title-case each word
    $words = $name.Split(' ')
    $titled = ($words | ForEach-Object {
        if ($_.Length -gt 0) {
            $_.Substring(0,1).ToUpper() + $_.Substring(1).ToLower()
        }
    }) -join ' '
    return $titled
}

# Regenerate photos.js manifest
Write-Host "Regenerating photos.js manifest..."

$lines = @()
$lines += "// ============================================================"
$lines += "// photos.js - Photo manifest (auto-generated by update-gallery.ps1)"
$lines += "// Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$lines += "// To add/remove photos: update the source folder and re-run"
$lines += "//   .\update-gallery.ps1"
$lines += "// ============================================================"
$lines += "window.PHOTOS = ["

$sortedFiles = $ImageFiles | Sort-Object Name
$fileCount = $sortedFiles.Count
$i = 0
foreach ($file in $sortedFiles) {
    $i++
    $caption = Get-Caption $file.Name
    $comma = if ($i -lt $fileCount) { "," } else { "" }
    $lines += "  { src: \"photos/$($file.Name)\", caption: \"$caption\" }$comma"
}

$lines += "];"

$lines | Set-Content -Path $ManifestPath -Encoding UTF8
Write-Host "photos.js updated with $fileCount photo(s)."
Write-Host ""

# Commit and push if enabled
if ($AutoCommitAndPush) {
    $gitAvailable = $null
    try { $gitAvailable = Get-Command git -ErrorAction Stop } catch {}

    if ($null -eq $gitAvailable) {
        Write-Warning "Git not found in PATH. Skipping commit/push."
        Write-Host "Install Git from https://git-scm.com/ and run again, or commit manually."
    } else {
        Write-Host "Committing and pushing changes to GitHub..."
        Push-Location $PSScriptRoot
        try {
            git add photos/ photos.js
            git commit -m $CommitMessage
            git push
            Write-Host ""
            Write-Host "Done! GitHub Pages will update within approximately 60 seconds."
            Write-Host "Gallery URL: https://mshikhar1.github.io/intranet-photo-gallery/"
        } catch {
            Write-Error "Git error: $_"
            Write-Host "Please commit and push manually:"
            Write-Host "  git add photos/ photos.js"
            Write-Host "  git commit -m 'Update gallery photographs'"
            Write-Host "  git push"
        }
        Pop-Location
    }
} else {
    Write-Host "AutoCommitAndPush is disabled."
    Write-Host "Commit and push manually:"
    Write-Host "  git add photos/ photos.js"
    Write-Host "  git commit -m 'Update gallery photographs'"
    Write-Host "  git push"
}

Write-Host ""
Write-Host "=== Update complete. ==="
Write-Host ""
